apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "75"
  generation: 75
  labels:
    app: accenture-bot_npm
  name: accenture-bot
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/accenture-bot
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: accenture-bot_npm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accenture-bot_npm
    spec:
      containers:
      - env:
        - name: CAMUNDA_URL
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: camunda-url-bot
        - name: RASA_URL
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: rasa-url-bot
        - name: APP_ID
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: app-id-bot
        - name: APP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: app-password-bot
        - name: INTENT_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: intent-threshold-bot
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: pg-database-bot
        - name: PG_USERNAME
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: pg-username-bot
        - name: PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: pg-password-bot
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: pg-host-bot
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: pg-port-bot
        - name: DIALECT
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: dialect-bot
        - name: SESSION_STORE
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: session-store-bot
        - name: SESSION_STORE_HOST
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: session-store-host-bot
        - name: SESSION_STORE_MASTERKEY
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: session-store-masterkey-bot
        - name: SESSION_STORE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: csession-store-database-bot
        - name: SESSION_STORE_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: session-store-collection-bot
        - name: SESSION_GZIP
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: session-gzip-bot
        - name: UPLOAD_STORAGE
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: upload-storage-bot
        - name: ACCESSKEYID
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: accesskeyid-bot
        - name: SECRETACCESSKEY
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: secretaccesskey
        - name: BOT_URL
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: bot-url-bot
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: region-bot
        - name: ROLE_BASED
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: role-based-bot
        - name: NODE_EXTRA_CA_CERTS
          valueFrom:
            configMapKeyRef:
              name: accenture-bot
              key: node-extra-ca-certs-bot
        image: accentureimgs.azurecr.io/accenturebot:88
        imagePullPolicy: IfNotPresent
        name: accenture-bot
        ports:
        - containerPort: 80
          name: http-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/rootCA.crt
          name: accenture-cert
          subPath: rootCA.crt
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: accenture-cert
        name: accenture-cert
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-17T10:27:02Z"
    lastUpdateTime: "2020-06-17T10:27:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 75
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
